export const LOAD_MOVIES_LOADING = "REDUX_THUNK_LOAD_MOVIES_LOADING";
export const LOAD_MOVIES_SUCCESS = 'REDUX_THUNK_LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_ERROR = 'REDUX_THUNK_LOAD_MOVIES_ERROR';
